#!/usr/bin/env zsh
#
# === {{CMD}} service-name new-dir
#
set -u -e -o pipefail

set "-x"
local +x SV_NAME="$1"; shift
local +x OLD_LOG="/var/service/${SV_NAME}_old"
local +x NEW_LOG="/var/service/${SV_NAME}"

# Remove the service. This also stops the log service if it exists.
if [[ -e /var/service/$SV_NAME ]]; then
  sudo sv stop $SV_NAME
  sudo rm -f /var/service/$SV_NAME
  process loop every 0.5 max 10 or until my_runit is-finished $SV_NAME
fi

while [[ "$(pgrep -f $SV_NAME | wc -l)" -lt 2 ]]; do
  sleep 0.5
done

if [[ -e "$OLD_LOG" ]]; then
  sudo rm -rf "$OLD_LOG"
fi

if [[ -e "$NEW_LOG" ]]; then
  sudo mv "$NEW_LOG" "$OLD_LOG"
fi

cd "$1"; shift
local +x NEW_DIR="$PWD"

find . -type f -name run | xargs -I NAME chmod +x NAME

sleep 2
sudo ln -s "$NEW_DIR" /var/service/$SV_NAME
